services:
  nuxt:
    build: .
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - NUXT_PUBLIC_POCKETBASE_URL=$POCKETBASE_URL
    networks:
      - shared_network

networks:
  shared_network:
    external: true
    name: apps-dragonflydb-zgbv7v